#!/bin/bash
# interactive non-login shell setup


for f in ~/.bash.d/rc/*; do
   source $f
done

export TEXINPUTS=./local//:

# export MANPATH=$HOME/Tools/share/man:`manpath -q`

for f in ~/.bash.d/functions/*; do
   source $f
done

if [ -f /opt/local/etc/bash_completion ]; then
   source /opt/local/etc/bash_completion
   for f in ~/.bash.d/completion/*; do
      source $f
   done
fi
