#!/bin/bash
# interactive non-login shell setup

# modularized portable configs
for f in ~/.bash.d/rc/*; do
   source $f
done


# ad-hoc stuff
export TEXINPUTS=./local//:


# utilities
for f in ~/.bash.d/functions/*; do
   source $f
done

for f in ~/.bash.d/completion/*.sh; do
   source $f
done

unset f
