#!/bin/bash
# interactive non-login shell setup

pathmunge () {
   local path=$1
   local new=$2
   if ! echo ${!path} | egrep -q "(^|:)$new($|:)" ; then
     if [ "$3" = "after" ] ; then
        export $path=${!path}:$new
     else
        export $path=$new:${!path}
     fi
   fi
}

# modularized portable configs
for f in ~/.bash.d/rc/*; do
   source $f
done


# ad-hoc stuff
export TEXINPUTS=./local//:


# utilities
for f in ~/.bash.d/functions/*; do
   source $f
done

for f in ~/.bash.d/completion/*.sh; do
   source $f
done

unset f
