set encoding=utf-8
set fileencoding=utf-8

syntax on
filetype on
filetype plugin on
filetype plugin indent on

set laststatus=2
set statusline=[%{GitBranch()}]\ %f%(\ %m%r%)%=%(%y\ %)%l,%v\ %p%%

set ignorecase
set smartcase
set incsearch
set hlsearch
set showmatch
set wildmenu
set ruler
set showcmd
set showmode
"set number
set wrap
set visualbell
set fillchars=""

" Sane defaults for tabs
set hidden
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set backspace=indent,eol,start
set cpoptions+=$ " mark changed area

nmap <F1> :NERDTreeToggle<CR>

" Create directories when saving
function WriteCreatingDirs()
    execute '!mkdir -p %:h'
    write
endfunction
command W call WriteCreatingDirs()

" Remove GUI menu and toolbar
set guioptions-=T
"set guioptions-=m
if(has("gui_running"))
    "colorscheme twilight2
    "colorscheme zenburn
    colorscheme railscasts
    set cursorline
    "set cursorcolumn
else
    set t_Co=256
    colorscheme railscasts
    "colorscheme vibrantink
    "colorscheme xoria256
    "colorscheme gentooish
endif

