Z=~/.zsh

fpath+=(
   $Z/functions
   $Z/completions
   $Z/lib
)

# module / dependency loading
function require() {
   for name ($*)
      autoload -Uz $name && $name
}

function provide() {
   for name ($*)
      function $name() { return 0; }
}

for config_file ($Z/rc/*.zsh)
   source $config_file

for function_file ($Z/functions/*)
   autoload -Uz ${function_file:t}
