#! /usr/bin/env zsh

PLUG=~/.vim/autoload/plug.vim
URL='https://raw.github.com/junegunn/vim-plug/master/plug.vim'

if [[ ! -d $PLUG ]]; then
    mkdir -p `dirname $PLUG`
    curl -fLo "$PLUG" "$URL"
fi

vim -u `dirname $0`/plugins.vim +PlugUpdate +q

