set nocompatible
set encoding=utf-8
set fileencoding=utf-8

" Load pathogen bundles
"let g:solarized_visibility = 'low'
"let g:solarized_hitrail = 1
let g:pathogen_disabled = []
if !has('ruby') || !has('gui_running')
    call add(g:pathogen_disabled, 'TeX-9')
endif
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Don't start autocomplpop too eagerly
let g:acp_behaviorKeywordLength = 3

" Prefix/namespace for user commands
let mapleader=";"

" Anticipating some common typos
function! CommandAlias(abbreviation, expansion)
    execute 'cabbr ' . a:abbreviation . ' <c-r>=getcmdpos() == 1 && getcmdtype() == ":" ? "' . a:expansion . '" : "' . a:abbreviation . '"<CR>'
endfunction
command! -nargs=+ CommandAlias call CommandAlias(<f-args>)
" Use it on itself to define a simpler abbreviation for itself.
CommandAlias alias CommandAlias
map q :q
CommandAlias Q q
CommandAlias qw wq

syntax on
filetype plugin indent on
set omnifunc=syntaxcomplete#Complete

set laststatus=2
let &statusline=' %f%( %y%m%r%)%=L%l C%v '
function StatuslineGitBranch()
    if exists('*GitBranch')
        let result = GitBranch()
        if result != ''
            return '[' . result . ']'
        endif
    endif
    return ''
endfunction
set statusline+=%(%{StatuslineGitBranch()}\ %)
if version >= 700
    " set the status line to flashy colors in insert mode
    autocmd InsertEnter * highlight StatusLine term=reverse ctermfg=15 ctermbg=9
    autocmd InsertEnter * highlight ModeMsg    term=reverse ctermfg=15 ctermbg=9
    autocmd InsertLeave * highlight StatusLine term=reverse ctermfg=14 ctermbg=0 gui=bold,reverse
    autocmd InsertLeave * highlight ModeMsg    term=NONE    ctermfg=4  ctermbg=NONE
    " unfortunately impossible to reuse the variables from solarized.vim
    "autocmd InsertEnter * exe "highlight! StatusLine" . s:fmt_none . s:fg_base3 . :bg_orange . s:fmt_revbb
    "autocmd InsertLeave * exe "highlight! StatusLine" . s:fmt_none . s:fg_base1 . s:bg_base01 . s:fmt_revbb
endif

set ignorecase
set smartcase
set incsearch
set hlsearch
set showmatch
set wildmenu wildmode=list:longest,full
set ruler
set showcmd
set showmode
"set number
set hidden
set wrap
set visualbell
set fillchars=""
set cursorline

" Integrate copy/paste with Mac OS
set clipboard=unnamed
"set mouse=a

" Sane indentation defaults
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent

set backspace=indent,eol,start
set cpoptions+=$ " mark changed area

nmap <F1> :NERDTreeToggle<CR>

" Sudo write that file!
command SudoWrite write !sudo tee % > /dev/null

" Invisible characters: shortcut to rapidly toggle
nmap <leader>i :set list!<CR>
set listchars=tab:▸\ ,eol:¬,trail:·,nbsp:_,extends:→,precedes:→
"highlight NonText guifg=#4a4a59
"highlight SpecialKey guifg=#4a4a59

" Unhighlight search results in normal mode
nmap <silent> <leader>n :silent nohlsearch<CR>

" Opening files relative to current one, e.g. :e %/bar.txt
cnoremap %% <C-r>=expand('%:p:.:h') . '/' <Enter>

" Remap line-exchange commands to match TextMate's shortcuts. Thanks to vimcasts.org for this :)
" Requires vim-unimpaired
nmap <C-Up> [e
nmap <C-Down> ]e
vmap <C-Up> [egv
vmap <C-Down> ]egv

" Create directories when saving
augroup BWCCreateDir
    autocmd!
    autocmd BufWritePre * if expand("<afile>")!~#'^\w\+:/' && !isdirectory(expand("%:h")) | execute "silent! !mkdir -p %:h" | redraw! | endif
augroup END

" Remove GUI menu and toolbar
set guioptions-=T
"set guioptions-=m
if(has("gui_running"))
    " Mac-like tab navigation
    map <D-S-]> gt
    map <D-S-[> gT
    
    set background=dark
    colorscheme solarized
    "colorscheme mustang
    "colorscheme railscasts
    "colorscheme twilight2
    "colorscheme vilight
    "colorscheme zenburn
    "set cursorcolumn
    highlight Cursor guibg=#eabf50
else
    "set t_Co=256
    set background=dark
    colorscheme solarized
    "colorscheme railscasts
    "colorscheme vibrantink
    "colorscheme xoria256
    "colorscheme gentooish
endif

" change default color of concealed contents
highlight clear Conceal
highlight default link Conceal Statement

