# -*- mode: sh -*-
Z=~/.zsh

# language options
setopt function_argzero

# module / dependency loading
# require: load & initialize a separate module
# provide: mark the module as loaded (if it does not provide an eponym function)
function require() { for name ($*) autoload -Uz $name && $name; }
function provide() { for name ($*) function $name() { return 0; }; }


fpath=($Z/lib $fpath)

# environment & shell interaction setup
for config_file ($Z/rc/*.zsh)
   source $config_file

rehash
