Z=~/.zsh

# language options
setopt function_argzero

# module / dependency loading
# require: load & initialize a separate module
# provide: mark the module as loaded (if it does not provide an eponym function)
function require() { for name ($*) autoload -Uz $name && $name; }
function provide() { for name ($*) function $name() { return 0; }; }

# locate / test for presence of a command
# dereference symlinks to help find homebrew packages
function find_command() {
    local found
    found=`which -ps $*` || return 1
    echo ${found##* -> }
}
function has_command() { find_command $* >/dev/null; }

fpath=($Z/lib $fpath)

# environment & shell interaction setup
for config_file ($Z/rc/*.zsh)
   source $config_file

rehash
