#! /usr/bin/env zsh

if ! gem list --installed jump &>/dev/null; then
   >&2 <<EOF
Jump is not installed!
Check your Ruby/RVM installation, or try:
   gem install jump
EOF
   return 1
fi

# fetch & load actual definition
local jump_setup=`gem contents jump | grep zsh_integration`
[[ -s "$jump_setup" ]] && source "$jump_setup" && jump "$*"
