#! /usr/bin/env zsh

local usage='Usage:  lmkdefault [-l] [[-a] file(s)]
Set or append to the list of documents built by latexmk'
local mode='@default_files = ('

local -a help append
zparseopts -D -K h=help a=append

if [[ $? != 0 || $# == 0 || -n $help ]]; then
    echo "$usage"
    return 0
fi
[[ -n $append ]] && mode='push @default_files, ('

echo -n "$mode '$1'" >> .latexmkrc
shift
for param; do
  echo -n ", '$param'" >> .latexmkrc
done
echo " );" >> .latexmkrc
