#!/usr/bin/env ruby
#
#  Created by Damien Pollet on 2006-08-02.
#  Copyright (c) 2006. All rights reserved.

flacs = ARGV[0] || '*.flac'

Dir.glob flacs do |flac|
  aiff = flac.gsub /\.flac$/, '.aiff'
  system 'flac', '--decode', "--output-name=#{aiff}", flac
end
