#!/bin/sh
# locate a blob in the commit history, given its SHA
# Inspired from http://stackoverflow.com/questions/460331/git-finding-a-filename-from-a-sha1
obj_name="$1"
shift
git log "$@" --date=short --pretty=format:'%T %h %cd %s' | while read tree commit date subject; do
    matches=$( git ls-tree -r $tree | grep "$obj_name" )
    if [ "$?" -eq 0 ]; then
        echo "$commit $date  $subject"
        echo "$matches" | cut -f2 | paste -d '\t\n' /dev/null -
    fi
done
