#!/usr/bin/env ruby
###
# update SCM checkouts

# per-extension update commands
UPDATE_COMMANDS = {
  '.gitclone' => 'git pull',
  '.hgclone' => 'hg pull',
  '.svn' => 'svn update',
  '.gitsvn' => 'git svn rebase'
}

require 'rubygems'
require 'rio'
require 'highlight'
String.highlighter = Text::ANSIHighlighter.new

class RIO::Rio
  def repo?
    return self.directory? && UPDATE_COMMANDS.has_key?(self.extname)
  end
end

if ARGV.empty?
  repositories = RIO.cwd.dirs[:repo?]
  if repositories.empty?
    here = RIO.cwd
    repositories = [ here ] if here.repo?
  end
else
  repositories = []
  ARGV.each do |arg|
    repo = rio(arg)
    repositories << repo if repo.repo?
  end
end

problems = {}
repositories.each do |repo|
  puts "Updating #{repo.filename}".cyan
  repo.chdir do
    system UPDATE_COMMANDS[repo.extname]
    problems[repo] = $? unless $?.success?
  end
end

unless problems.empty?
  puts "Problems:".bold.red
  problems.each do |repo, status|
    puts "#{status.to_s.rjust(3).cyan}  #{repo.filename}"
  end
end
