#!/bin/bash

prefix="/Library/Application Support/TextMate"
svnUrl="http://svn.textmate.org/trunk"

svnProjects=( \
	Bundles \
	PlugIns \
	Support \
	Themes \
	)

gitBundles=( \
	Git=git://gitorious.org/git-tmbundle/mainline.git \
	smalltalk=git://github.com/AntonyBlakey/smalltalk.tmbundle.git \
	cweb=git://github.com/michaelmelanson/cweb-tmbundle.git \
	sass=git://github.com/aussiegeek/ruby-sass-tmbundle.git \
	clojure=git://github.com/nullstyle/clojure-tmbundle.git
	)

function initialize() {
	echo "No bundles in ${prefix}, checking them out from scratch"
	mkdir -p "${prefix}"
	cd "${prefix}"
	for p in ${svnProjects[@]}; do
		svn checkout ${svnUrl}/${p}
	done
	for b in ${gitBundles[@]}; do
		bundle="Bundles/${b%%=*}.tmbundle"
		if [[ -d ${bundle}/.svn ]]; then
			echo "${bundle} already here from SVN, not overwriting from Git"
		else
			git clone ${b#*=} Bundles/${b%%=*}.tmbundle
		fi
	done
}

function update() {
	echo "Updating bundles in ${prefix}"
	cd "${prefix}"
	for p in ${svnProjects[@]}; do
		echo "SVN: ${p}"
		svn update ${p}
	done
	for b in ${gitBundles[@]}; do
		bundle="Bundles/${b%%=*}.tmbundle"
		if [[ -d ${bundle}/.svn ]]; then
			echo "${bundle} already here from SVN, not updating with Git"
		else
			echo "Git: ${bundle}"
			pushd ${bundle} >/dev/null
			git pull
			popd >/dev/null
		fi
	done
}

function reload() {
	if (killall -s TextMate > /dev/null); then # only reload if TM is running
		echo 'Reloading bundles'
		osascript -e 'tell application "TextMate" to reload bundles'
	fi
}

export LC_CTYPE=en_US.UTF-8
if [[ ! -d "${prefix}" ]]; then
	initialize
else
	update
fi
reload
